### ISSUE TITLE
Run TBProfiler

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/drprg#10]
Run TBProfiler on the isolates we select from https://github.com/mbhall88/drprg-paper/issues/1

The first part of this will be making a TBProfiler panel from our panel so that we are using the same.

**Comment by mbhall88** [comment]
Actually, an important question here is whether we use TBProfiler's built in catalogue...

From the mykrobe paper

> In order to separate the impact of catalogue from the different genotyping processes applied by different methods, we modified ARIBA to use the same catalogue as Mykrobe, but for the other tools we used their in-built catalogues.

If we want to really understand how much the methodology impacts the performance though we should use the same catalogue right?

Instructions on how to build a custom TBProfiler catalogue are at https://jodyphelan.gitbook.io/tb-profiler/quickstart/mutation-library. The main pain point with this will be that TBProfiler wants the variants in hgvs nomenclature, so I will have to convert mykrobe's variant format to hgvs.

**Comment by iqbal-lab** [comment]
I think same catalogue,  and WHO to boot, is fine surely

**Comment by mbhall88** [comment]
Sorry, I'm actually a little confused by what you just said...Got lost in the English-to-Australian translation?

**Comment by iqbal-lab** [comment]
Sorry, I'm just suggesting you use the same catalogue for both tools. Since the Mykrobe catalogue includes the WHO panel, I expect reviewers will see that as a positive. 

Running both tools with both Mykrobe and TB profiler panels would be technically interesting but I propose don't bother.
