### ISSUE TITLE
Benchmark figures

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/drprg#15]
Create benchmark figures for time and memory usage. 

How do we want to do time? CPU time, wall time? I guess this gets complicated by threads, although I am using 2 for each tool at the moment.

**Comment by mbhall88** [comment]
Okay, so this is what I have for the nanopore data. Anything we want changed?

### Runtime

![image](https://user-images.githubusercontent.com/20403931/195257678-cde00e5c-8d00-4b2b-b807-cd266b75e77a.png)

### Max. RAM usage

![image](https://user-images.githubusercontent.com/20403931/195257695-4863394e-9a86-4c5c-9c9c-d1c1365a2854.png)

**Comment by lachlancoin** [comment]
Nice visualisation

**Comment by iqbal-lab** [comment]
Looks great. Nothing to change,  though I'm wondering what the p values are testing

**Comment by lachlancoin** [comment]
Just testing whether the means of the distributions are equal.  Pretty
clear they are not from the plot but I guess it helps if you want to say
"significantly different" .  I guess you used an unpaired t-test, but
actually they are paired data (same sample using different approaches) If
anything that should make the pvalues even more significant.

**Comment by mbhall88** [comment]
I used a [wilcoxon signed-rank test](https://en.wikipedia.org/wiki/Wilcoxon_signed-rank_test). Basically the nonparametric version of a paired t-test (because I'm lazy and couldn't be bothered testing for normality 😅 )

> Pretty clear they are not from the plot but I guess it helps if you want to say "significantly different"

It wasn't actually clear to me that the runtimes would be significantly different for drprg and mykrobe

**Comment by mbhall88** [comment]
Here are the Illumina figures. These aren't final as this is only a subset of 400 samples, but I can't imagine it will change dramatically.

### Memory

![image](https://user-images.githubusercontent.com/20403931/195477019-1bc01151-342c-4f43-9159-4729599c4993.png)


### Runtime

![image](https://user-images.githubusercontent.com/20403931/195477181-b9bf25de-706c-46f7-a446-4445ba9878fd.png)

**Comment by mbhall88** [comment]
The latest figures after adding in the racon denovo from https://github.com/rmcolq/pandora/pull/299 can be seen in https://github.com/rmcolq/pandora/issues/303#issuecomment-1305098855
