### ISSUE TITLE
Targeted sequencing mode

### ISSUE THREAD

**Issue by mbhall88** [mbhall88/drprg#25]
Implementation of this feature will rely on the successful resolution of https://github.com/rmcolq/pandora/issues/263 for starters.

In addition, we will probably need to require a BED file of the regions targeted by the user so that we don't trigger things like whole/partial gene deletions in samples where the whole gene was no amplified. This will also alllow us to set the correct genome size for the sample in pandora.

One last question is whether we should include this in the paper or delay it until after the paper (and maybe do a follow-up paper describing the results)? cc @lachlancoin @iqbal-lab

**Comment by iqbal-lab** [comment]
Kneejerk reaction is to say it belongs in a follow-up; I'd be keener to get the "start of gene is deleted" issue fixed for the first paper if that were possible
