### ISSUE TITLE
Paired-end fastq files

### ISSUE THREAD

**Issue by erinyoung** [mbhall88/drprg#37]
My apologies if this is in the documentation somewhere, but I am unable to figure out how to run drprg on two fastq files at the same time. 

```
drprg predict -x mtb -i reads.fq --illumina -o outdir/
```
^ only has one fastq file.

**Comment by mbhall88** [comment]
Hi. Yep this is mentioned in the docs here https://mbh.sh/drprg/guide/predict.html#input-reads
