### ISSUE TITLE
Missing expected output file /test/outdir/discover/denovo_sequences.fa

### ISSUE THREAD

**Issue by erinyoung** [mbhall88/drprg#38]
I fear I may be missing something.

This is the set of commands that I used:
```bash
# downloading some TB reads (works fine)
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR230/005/SRR23086705/SRR23086705_1.fastq.gz

# getting the index (works fine)
drprg index --download mtb

# running predict (fails)
drprg predict -x mtb -i SRR23086705_1.fastq.gz --illumina -o outdir/
```

This is the error from drprg predict
```
11.12 [2023-11-14T23:44:10Z INFO ] Outdir doesn't exist...creating...
11.12 [2023-11-14T23:44:10Z INFO ] Discovering variants...
36.82 Error: Failed to update discover PRG
36.82 
36.82 Caused by:
36.82     Missing expected output file /test/outdir/discover/denovo_sequences.fa
```

Is there something I can do to get `drprg predict` to run to completion? I fear I have missed something in the documentation somewhere.

**Comment by mbhall88** [comment]
Hi @erinyoung 

I can't seem to reproduce this issue. I ran your exact commands and the run completed successfully.

Which version are you using and how did you install drprg?

**Comment by erinyoung** [comment]
I installed Dr. PRG from source (or so I thought). I installed rasusa, seqfu, pandore, mafft, bcftools, and make_prg from source as well. Do you have an idea as to which dependency wasn't installed correctly? (All of their help messages work.)

**Comment by erinyoung** [comment]
My apologies, I need to amend my comment. 

I downloaded the binaries for pandora, make_prg, drprg, seqfu, and rasusa. I built bcftools from source and downloaded the deb file for mafft and installed it that way.

**Comment by mbhall88** [comment]
It will be Pandora giving the error and it will depend on which version of Pandora you used. drprg relies on a very specific version. There's a `just` recipe that will download the right one if you run `just pandora`, or you can see the URL here https://github.com/mbhall88/drprg/blob/ef65d4a46e2a31cc268d4e5a106fbce72fb95e0e/justfile#L17

FYI when i tried to recreate your issue I used the conda recipe for drprg. You could also try the container if that's an option for you.

**Comment by erinyoung** [comment]
My apologies! I realized I never told you that I resolved my issues by reinstalling pandora!
